### ISSUE TITLE
Leverage Type Introspection (via edgedb-rust) with Deserialized ESDL AST (via Python EDB)

### ISSUE THREAD

**Issue by dmgolembiowski** [dmgolembiowski/edgemorph#10]
## Abstract
We propose to use ESDL abstract syntax trees as the basis for code generation in the Edgemorph framework.

***
## Motivation
To Edgemorph, EdgeDB's compiler is the root of all magic. By digesting an SDL module into AST tokens, we share a common tongue between any supported programming language. To this end, it is reasonable to use a strongly-typed programming language like Rust or TypeScript to build boilerplate code structures from a user's schema definitions. 

![edgedb_bullet_train](https://raw.githubusercontent.com/dmgolembiowski/edgemorph/master/.github_assets/train.jpg)
<p style='text-align: right;'><i><b>Warning: Do not stand in front of the EdgeDB bullet train.</b></i></p>

Since EdgeDB's capabilities continue to rapidly evolve, and since its SDL language continues to mature in ways that enrich each user's experience, it becomes imperative for Edgemorph to jump out of the way and trek behind — following the smokestacks. We do this by capturing abstract syntax structures during the `edm make` process, and disk-cache them for interpretation during `edm make install`.

We believe this approach offers the greatest amount of backward and forward compatibility between successive EdgeDB version releases — because each tag (i.e. alpha-3, alpha-4, ... ) will correspond to its own variant of AST deserialization requirements. Moreover, whenever EdgeDB announces a new release, e.g. version alpha-_**N**_, AST changes resulting from alpha-_**N**_'s release will only need to be developed on a fork of the latest Edgemorph edition (the one corresponding to EdgeDB version alpha-_**N - 1**_ ).

To be clear, this is a high-effort, high-maintenance approach but the tradeoff is guaranteed backwards compatibility with EdgeDB.

***
## Type Specifications

The purpose of this RFC's Abstract Specifications section is to identify generic templates that will be coded in Rust. For example, the serialized abstract syntax below must have each of its fields meaningfully converted into a Rust type at compile time. _(Note: The following list of types is not complete, but it does cover the most common AST token kinds.)_

<p style='text-align: right;'><i><b>Example of a serialized module's abstract syntax tree</b></i></p>

> <TreeNode id=139713944389664, name='ModuleDeclaration', children=edb.common.checked.CheckedList[edb.common.markup.elements.lang.TreeNodeChild]([<TreeNodeChild id=None, label='name', node=<TreeNode id=139713904379744, name='ObjectRef', children=edb.common.checked.CheckedList[edb.common.markup.elements.lang.TreeNodeChild]([<TreeNodeChild id=None, label='name', node=<String str='etest' at 0x7f119fe79880> at 0x7f119ed86580>]) at 0x7f119ed86100> at 0x7f119f0cb400>, <TreeNodeChild id=None, label='declarations', node=<List id=139713904382336, items=edb.common.checked.CheckedList[edb.common.markup.elements.base.Markup]([<TreeNode id=139713904380176, name='CreateObjectType', children=edb.common.checked.CheckedList[edb.common.markup.elements.lang.TreeNodeChild]([<TreeNodeChild id=None, label='name', node=<TreeNode id=139713904380224, name='ObjectRef', children= ...

***
#### `TreeNode`
- `id`: `<i32>`
- `name`: _N<sub>T</sub>_ such that _N<sub>T</sub>_ &#8712; _T **&acute;**_ and  _T **&acute;**_ satisfies the size requirements for each of the following identifiers. :
> ```python  
> { 'BinOp',
>   'CreateAlias', 
>   'CreateConcreteLink', 
>   'CreateConcreteProperty',
>   'CreateFunction',
>   'CreateIndex',
>   'CreateLink', 
>   'CreateObjectType', 
>   'CreateScalarType',
>   'ForQuery',
>   'FuncParam',
>   'FunctionCall', 
>   'FunctionCode',
>   'InsertQuery', 
>   'IntegerConstant',
>   'ModuleAliasDecl', 
>   'ModuleDeclaration',
>   'ObjectRef', 
>   'Path', 
>   'Ptr',
>   'Schema', 
>   'SelectQuery', 
>   'Set',
>   'SetAnnotation',
>   'SetField', 
>   'ShapeElement', 
>   'ShapeOperation',
>   'StringConstant', 
>   'TypeCast', 
>   'TypeName' }  
> ```
- `children`: `CheckedList<TreeNodeChild, Markup>`
***
#### `TreeNodeChild`
- `id`: `Optional<i32>`
- `label`: `String` _s_, such that _s_  &#8712; _L_ &equals; `{ "name", "target", "maintype" }`
- `node`: `enum <String ; TreeNode; List >`, with the following corollaries:
  -  `node::String` &#8594; `<String str = '%s'>`;
  - `node::TreeNode` &#8594; `&'a Sized<RefCell<Weak<TreeNode<'a>>>>`. **_'a_** is the lifetime specifier for the `TreeNode` it ellides. `Sized<T>` is a type with known size. `RefCell<T>` is a mutable memory location with dynamically checked borrow rules<sup>1</sup>. `Weak<T>` is a pointer that holds a non-owning reference to the managed allocation<sup>2</sup>. [`TreeNode`](https://github.com/edgedb/edgedb/blob/ff869ab54d63968081d54e99b4dfb8f2b62f9ce8/edb/common/markup/elements/lang.py#L81) is an EdgeDB language markup base object subtype.

***
#### `Schema`
- `declarations`: `Vec<ModuleDeclaration>`
***
#### `ModuleDeclaration`
- `name`: `ObjectRef<&str>`
- `declarations`: `Vec<Declaration>`
***
#### `Declaration`
- `CreateAlias`:
  ```rust
  
- `CreateObjectType`:
  ```rust
  name: String,
  commands: Vec<CreateConcreteProperty> | Vec<CreateConcreteLink>
  ```
- `CreateFunction`:
  ```rust
  name: String
  params: Vec<FuncParam>
  returning: Optional<TreeNodeChild>
  returning_typemod: Optional<TreeNodeChild>
  ```
***
#### `BinOp`
- `left`: `Expr`
- `op`: `String`
- `right`: `String`
***
### Implementation Considerations
It can be difficult to write a parser for any complex serialized AST where all types must have known sizes at compile time. While a _"TT (token tree) Muncher"_ seems like a viable option, the practicality of a TT muncher at this scale is brutal. The sheer volume of terms and tokens to match (or discard) makes this difficult to maintain. A more suitable approach would be to write the deserializer with some formal grammar modularity. My preference leans toward PEG and Pest. 

Regardless of the approach taken for the intermediate deserialization step, Edgemorph will either need to create the innermost leaf nodes and run `to_owned()` once inside their owner's `::new(...)` method, or Edgemorph could adapt the builder methods in `datastructures.rs` to stitch distinct nodes together within their owners. Lastly, Edgemorph could operate upon the AST and match against a giant `enum`-like structure to allocate each of the codegen Rust types.

### References
1. [std::cell::RefCell](https://doc.rust-lang.org/std/cell/struct.RefCell.html)
2. [std::rc::Weak](https://doc.rust-lang.org/std/rc/struct.Weak.html)

**Comment by dmgolembiowski** [comment]
@tailhook, do you have any suggestions on this topic:
> ### Implementation Considerations
> It can be difficult to write a parser for any complex serialized AST where all types must have known sizes at compile time. While a _"TT (token tree) Muncher"_ seems like a viable option, the practicality of a TT muncher at this scale is brutal. The sheer volume of terms and tokens to match (or discard) makes this difficult to maintain. A more suitable approach would be to write the deserializer with some formal grammar modularity. My preference leans toward PEG and Pest.
> 
> Regardless of the approach taken for the intermediate deserialization step, Edgemorph will either need to create the innermost leaf nodes and run `to_owned()` once inside their owner's `::new(...)` method, or Edgemorph could adapt the builder methods in `datastructures.rs` to stitch distinct nodes together within their owners. Lastly, Edgemorph could operate upon the AST and match against a giant `enum`-like structure to allocate each of the codegen Rust types.

I'd rather know ahead of time if I'm entering the danger zone

**Comment by dmgolembiowski** [comment]
ToDo: Revise pre-RFC to include multi-module validation using EdgeQL introspection. In particular, referencing outside user-defined SDL modules within another SDL module is not checked by the ql_parser.

**Comment by tailhook** [comment]
> @tailhook, do you have any suggestions on this topic:

I'm not sure I understand matters here. But have you considered using edgedb introspection for codegen?
I.e. you apply the schema into the edgedb instance and then execute queries. Here is how you can get all the properties of the `User` object:
```
SELECT schema::ObjectType {
    properties: {name}
}
FILTER .name = 'default::User';
```
More docs here: https://www.edgedb.com/docs/edgeql/introspection/objects

-----

We are going to rewrite EdgeQL parser in Rust at some point, so tying your implementation to specific python AST now might introduce more churn than needed.

**Comment by dmgolembiowski** [comment]
> We are going to rewrite EdgeQL parser in Rust at some point, so tying your implementation to specific python AST now might introduce more churn than needed.

Excellent; Yury also shared some useful points with me in another conversation related to this pre-RFC. Introspection seems to be the way to go, so I'll table this issue until the Rust EdgeQL parser is stable. Thank you!

**Comment by dmgolembiowski** [comment]
>>> Have you considered applying the schema into the live EdgeDB and then using [introspection](https://www.edgedb.com/docs/edgeql/introspection/index) for getting type info for making codegen? Or do you use edgedb submodule for different purposes?
>> 
>> No, I hadn't considered that. Thanks for the suggestion; it may come in handy once I begin the `edm` port to rust. I chose this approach because back when alpha-1 or alpha-2 and I was just getting started, I realized it wasn't convenient enough to check syntax for validity unless you were already on the CLI.
>> At those earlier versions, the error reporting was less refined than it is now, so debugging was a chore.
>> But for compilation I'm using the _edgedb.edb_ submodule to deserialize a user's module files into AST so that only valid schemas can be "installed".
>> For the time being, it's a smelly to hack the non-public submodule into edgemorph, but it's only temporary

>> Oh, I've seen this comment after commenting about the same in another issue. You may disregard that comment.
> _Originally posted by @tailhook in https://github.com/dmgolembiowski/edgemorph/pull/8#issuecomment-717112607_

Type introspection should work in concert with markup serialization and EDB QL parsing.

Reopening this pre-RFC with the knowledge that QL parsing is already provided by the EdgeDB submodule via:
```python
from edb.common.markup import _serialize as serialize
from edb.edgeql import parser as qlparser
```

**Comment by dmgolembiowski** [comment]
Supplying more complete `TreeNodeName` name fields, per https://github.com/edgedb/edgedb/blob/ce2f48d6be3a4111069ef4040694003ed7ac3c51/edb/edgeql/parser/grammar/sdl.py
