### ISSUE TITLE
Reconsider Python API (post PEP-614)

### ISSUE THREAD

**Issue by dmgolembiowski** [dmgolembiowski/edgemorph#2]
With the stable release of Python 3.9, it's helpful to discuss supplemental improvements to the edgemorph (framework? library?) Python API. Because 3.9 allows more permissive decorator grammar with [PEP 614](https://www.python.org/dev/peps/pep-0614/), I'm excited about ways in which SDL functions can be expressed on modules.

Truly, this blows the gates wide open.
With this enhancement, it is possible to use decorators (both for the type implementation classes and the SDL functions) in an entirely new, more expressive way.

```python
buttons = [QPushButton(f'Button {i}') for i in range(10)]

# Do stuff with the list of buttons...

@buttons[0].clicked.connect
def spam():
    ...

@buttons[1].clicked.connect
def eggs():
    ...

# Do stuff with the list of buttons...
```

From the excerpt, we can infer that it's possible to call `__getitem__`-derived methods -- leveraging new patterns for `@index_on.<some field>`, `@constraint.(abs=True)`, etc.

CPython implementation details are available at: https://github.com/python/cpython/pull/18570

**Comment by nsidnev** [comment]
Hmm, I'm still not sure about decorators, but if `edgemorph` takes this approach, then maybe `edm` can also generate appropriate typing for it in the `*.pyi` files?
Also, using this functionality will force us to pin python to "^ 3.9" version, which will severely limit the use of `edgemorph`.

**Comment by dmgolembiowski** [comment]
You're right; thank you for bringing that up. We could re-open this issue after 3.10 or 4.0 becomes stable.
